config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sports, only: %i[index]
  resources :teams, only: %i[index]
  resources :favorite_sports, only: %i[create destroy]
  resources :followed_teams, only: %i[create destroy]
  resources :about, only: :index
  # Defines the root path route ("/")
  root "sports#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/odds.rb
# frozen_string_literal: true

module Odds
  extend ActiveSupport::Concern

  def full_string_of_money_lines_for_sport
    next_24_hour_matches.flat_map do |match|
      money_lines = money_lines_for_match(match)
      money_lines_strings_for_match(money_lines)
    end.join("\r\n")
  end

  def next_24_hour_matches
    JSON.parse(OddsApi.new.odds_for_sport(self)).select do |match|
      time = Time.zone.parse(match['commence_time'])
      time.future? && time - Time.now.utc < 86_400
    end
  end

  def money_lines_for_match(match)
    match['bookmakers'].first&.dig('markets')&.select do |market_hash|
      market_hash['key'] == 'h2h'
    end
  end

  def money_lines_strings_for_match(money_lines)
    money_lines.flat_map do |money_line_hash|
      money_line_hash['outcomes'].flat_map do |outcome|
        "#{outcome['name']}: #{odds_with_plus_or_minus(outcome['price'])}"
      end
    end.join(' | ')
  end

  def odds_with_plus_or_minus(price)
    return price if price.negative?

    "+#{price}"
  end
end


# sport = Sport.find_by(key: 'baseball_mlb')
# sport.full_string_of_money_lines_for_sport
# sport.next_24_hour_matches.map{|hash| "#{hash['home_team']} vs #{hash['away_team']}"}

app/models/followed_team.rb
# frozen_string_literal: true

class FollowedTeam < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/sport.rb
# frozen_string_literal: true

class Sport < ApplicationRecord
  CURRENT_OFFERINGS = %w[MLB ATP NBA WTA].freeze

  has_many :user_favorites, dependent: :destroy
  has_many :users, through: :user_favorites
  has_many :team_sports, dependent: :destroy
  has_many :teams, through: :team_sports

  validates :key, uniqueness: true

  scope :active, -> { where(active: true) }
  scope :with_rank, -> { where.not(popularity_rank: nil) }
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :team_sports, dependent: :destroy
  has_many :followed_teams, dependent: :destroy

  validates :name, presence: true
end

app/models/team_sport.rb
# frozen_string_literal: true

class TeamSport < ApplicationRecord
  belongs_to :team
  belongs_to :sport
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_favorites, dependent: :destroy
  has_many :sports, through: :user_favorites
  has_many :followed_teams, dependent: :destroy
  has_many :teams, -> { distinct }, through: :followed_teams

  validates :phone_number, presence: true, numericality: true, length: { is: 10 }

  def send_message
    message = all_lines_message
    return if message.blank?

    TwilioApi.new(user: self, message:).send_message
  end

  def all_lines_message
    all_line_messages_grouped_by_sport.map do |sport_title, line_message|
      "#{sport_title}\r\n#{line_message}"
    end.join("\r\n\r\n")
  end

  def all_line_messages_grouped_by_sport
    sports.each_with_object({}) do |sport, hash|
      message = MessageForSport.new(user: self, sport:).message
      next if message.blank?

      hash[sport.title] = message
    end
  end
end

app/models/user_favorite.rb
# frozen_string_literal: true

class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :sport

  after_destroy :remove_followed_teams

  def remove_followed_teams
    return if user.sports.exists?(team_group: sport.team_group)

    user.followed_teams.where(team_id: sport.teams.pluck(:id)).destroy_all
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favorite_sports_controller.rb
# frozen_string_literal: true

class FavoriteSportsController < ApplicationController
  def create
    sport = Sport.find_by(title: params[:title])
    UserFavorite.create(user: current_user, sport:)
    set_sports

    respond_to :turbo_stream
  end

  def destroy
    sport = Sport.find(params[:id])
    user_favorite = UserFavorite.find_by(user: current_user, sport:)
    user_favorite.destroy
    set_sports

    respond_to :turbo_stream
  end

  private

  def set_sports
    sports = Sport.all
    @favorited_sports = Sport.joins(:user_favorites).where(user_favorites: { user_id: current_user.id }).distinct
    sports -= @favorited_sports
    @sports_hash = sports.group_by(&:team_group)
  end
end

app/controllers/followed_teams_controller.rb
# frozen_string_literal: true

class FollowedTeamsController < ApplicationController
  def create
    team = Team.find_by(name: params[:name])
    current_user.followed_teams.create(team:)
    set_teams

    respond_to :turbo_stream
  end

  def destroy
    followed_team = FollowedTeam.find_by(user: current_user, team: params[:id])
    followed_team.destroy
    set_teams

    respond_to :turbo_stream
  end

  private

  def set_teams
    sports = current_user.sports
    teams = sports.flat_map(&:teams).uniq
    followed_teams = current_user.teams
    teams -= followed_teams
    @teams_hash = teams.group_by(&:sport_group)
    @followed_teams_hash = followed_teams.group_by(&:sport_group)
  end
end

app/controllers/sports_controller.rb
# frozen_string_literal: true

class SportsController < ApplicationController
  def index
    sports = Sport.all
    @favorited_sports = Sport.joins(:user_favorites).where(user_favorites: { user_id: User.first.id }).distinct
    sports -= @favorited_sports
    @sports_hash = sports.group_by(&:team_group)
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  def index
    sports = current_user.sports
    teams = sports.flat_map(&:teams).uniq
    followed_teams = current_user.teams
    teams -= followed_teams
    @teams_hash = teams.group_by(&:sport_group)
    @followed_teams_hash = followed_teams.group_by(&:sport_group)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/favorite_sports_helper.rb
# frozen_string_literal: true

module FavoriteSportsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true
module TeamsHelper
  def button_color(sport_group)
    case sport_group
    when 'MLB'
      'bg-red-500'
    when 'NBA'
      'bg-blue-500'
    when 'ATP'
      'bg-lime-500'
    when 'WTA'
      'bg-violet-500'
    end
  end
end

app/views/about/index.html.slim
.h-screen
  .pb-5.text-4xl.text-center.font-semibold.text-neutral-600 Never miss your moneylines again!
  .py-5.text-3xl.text-center.font-semibold.text-neutral-600 First follow your sports
  .flex.justify-center = image_tag('about.gif', class: 'pb-5 drop-shadow-2xl hidden lg:block w-10/12')
  .flex.justify-center = image_tag('mobile_about.gif', class: 'pb-5 drop-shadow-2xl block lg:hidden w-10/12')
  .py-5.text-3xl.text-center.font-semibold.text-neutral-600 Then receive a daily text with moneylines
  .flex.justify-center = image_tag('text.png', class: 'pb-5 drop-shadow-2xl block lg:hidden w-10/12 lg:w-1/2')
  .flex.justify-center = image_tag('text2.png', class: 'pb-5 drop-shadow-2xl hidden lg:block w-10/12 lg:w-1/2')

app/views/favorite_sports/create.turbo_stream.erb
<%= turbo_stream.replace :sports do %>
  <%= render "sports/sports", sports_hash: @sports_hash, favorited_sports: @favorited_sports %>
<% end %>

app/views/favorite_sports/destroy.turbo_stream.erb
<%= turbo_stream.replace :sports do %>
  <%= render "sports/sports", sports_hash: @sports_hash, favorited_sports: @favorited_sports %>
<% end %>

app/views/followed_teams/create.turbo_stream.erb
<%= turbo_stream.replace :teams do %>
  <%= render "teams/teams", teams_hash: @teams_hash, followed_teams_hash: @followed_teams_hash %>
<% end %>

app/views/followed_teams/destroy.turbo_stream.erb
<%= turbo_stream.replace :teams do %>
  <%= render "teams/teams", teams_hash: @teams_hash, followed_teams_hash: @followed_teams_hash %>
<% end %>

app/views/layouts/_alert.html.slim
- if alert
  div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"
    strong> class="font-bold" Jeepers creepers!
    span class="block sm:inline" = alert

app/views/layouts/_navbar.html.slim
nav class="z-10 sticky top-0 relative flex w-full flex-wrap items-center justify-between py-2 text-neutral-500 shadow-lg focus:text-neutral-700 bg-neutral-100 lg:py-4"
  div class="flex w-full flex-wrap items-center justify-between px-3"
    div class="ml-3"
      = image_tag('calc2.png', class: 'h-10 my-0 mr-2 inline-block')
      = link_to "OddsPal", root_path, class: "inline-block align-middle text-2xl font-semibold text-neutral-800"
    div class="mr-3"
      = link_to "about", about_index_path, class: "mr-4 hover:text-neutral-700"
      - if user_signed_in?
        = link_to "logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "hover:text-neutral-700"
      - else
        = link_to "login", new_user_session_path, class: "hover:text-neutral-700"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OddsPal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="facebook-domain-verification" content="4zqnz7yqe0basa2h1qj7xncj3y7qqu" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('calc2.png') %>
  </head>

  <body class="bg-gray-200">
    <%= render 'layouts/navbar' %>
    <main class="container mx-auto mt-28 px-5">
      <%= render 'layouts/alert' %>
      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/sports/_sports.html.slim
= turbo_frame_tag :sports do
  .space-y-3
    - if current_user.user_favorites.exists?
      .text-2xl.font-semibold.text-neutral-800 Followed sports
      div
        - favorited_sports.each do |sport|
          .inline-block.m-1 = link_to sport.title, favorite_sport_path(sport), class: "#{button_color(sport.team_group)} text-white py-1 px-2 rounded", data: { turbo_method: :delete }

    .text-2xl.font-semibold.text-neutral-800 Available sports
    div
      - sports_hash.each do |sport_group, sports|
        p = sport_group
        - sports.each do |sport|
          .inline-block.m-1 = link_to sport.title, favorite_sports_path(title: sport.title), class: "#{button_color(sport.team_group)} text-white py-1 px-2 rounded",  data: { turbo_method: :post }

app/views/sports/index.html.slim
= render 'sports', sports_hash: @sports_hash, favorited_sports: @favorited_sports

= link_to 'Refine selections', teams_path, class: 'float-left mt-5 mb-20 inline-flex items-center font-medium text-blue-600 dark:text-blue-500 hover:underline'